backbone: mymodel
data_aug: true
data_path: /home/jchen152/workspace/Data/ModelNet40_C_fewshot
decay_ep: 5
device: cuda
epochs: 80
exp_folder_name: ModelNet40_C_cross
exp_name: Mymodel_5k1s10q_fold3_scale_0.7
fold: 3
fs_head: trip
gamma: 0.7
k_way: 5
lr: 0.0001
lr_sch: false
multigpu: false
n_shot: 1
project_path: /home/jchen152/workspace/Few_Shot_Point_Cloud
query: 10
seed: 0
train: true
