backbone: mymodel
data_path: /home/jchen152/workspace/Data/modelnet40_fs/modelnet40_ply_hdf5_2048_fs
decay_ep: 5
device: cuda
epochs: 80
exp_name: mymodel+trip_moreview
fs_head: trip
gamma: 0.5
k_way: 5
lr: 0.0001
lr_sch: false
n_shot: 1
project_path: /home/jchen152/workspace/Few_Shot_Point_Cloud
query: 5
seed: 0
train: true
