backbone: dgcnn
data_aug: true
data_path: /home/jchen152/workspace/Data/ShapeNet
decay_ep: 5
device: cuda
epochs: 80
exp_folder_name: ShapeNet_cross
exp_name: CIA_5k5s10q_fold4_fixR
fold: 4
fs_head: cia
gamma: 0.7
k_way: 5
lr: 0.0001
lr_sch: false
multigpu: false
n_shot: 5
project_path: /home/jchen152/workspace/Few_Shot_Point_Cloud
query: 10
seed: 0
train: true
