backbone: dgcnn
data_aug: true
data_path: /home/jchen152/workspace/Data/ScanObjectNN_fs_crossvalidation/ScanObjectNN_fs_cross_validation/Data
decay_ep: 5
device: cuda
epochs: 80
exp_folder_name: ScanObjectNN_cross
exp_name: CIA_5k5s10q_fold1_fixR
fold: 1
fs_head: cia
gamma: 0.7
k_way: 5
lr: 0.0001
lr_sch: false
multigpu: false
n_shot: 5
project_path: /home/jchen152/workspace/Few_Shot_Point_Cloud
query: 10
seed: 0
train: true
